#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

usage() {
  cat <<'EOF'
用法：
  00-setup-ssh-wol.sh configure   在当前控制端生成 SSH 配置片段和 WOL 代理
  00-setup-ssh-wol.sh check       检查本地配置、密钥和生成文件

说明：
  - 只修改当前控制端的 ~/.ssh；不会复制私钥、修改远端或运行远端 sudo。
  - WOL 广播地址和目标 MAC 必须先写入本地 .env；模板不会提供真实值。
  - 远端 Remote Login、authorized_keys、pmset 和 ~/.ssh/rc 按 README 手动完成。
EOF
}

die_config() {
  die "$1；请在 .env 中设置对应 WHISPER_SSH_* / WHISPER_WOL_* 参数。"
}

require_macos() {
  [[ "$(uname -s)" == "Darwin" ]] || die "SSH/WOL 配置脚本只支持 macOS 控制端。"
}

validate_scalar() {
  local name="$1" value="$2"
  [[ -n "${value}" ]] || die_config "${name} 不能为空"
  [[ "${value}" != *$'\n'* && "${value}" != *$'\r'* ]] || die_config "${name} 不能包含换行"
}

validate_config() {
  validate_scalar WHISPER_SSH_ALIAS "${WHISPER_SSH_ALIAS}"
  validate_scalar WHISPER_SSH_HOST "${WHISPER_SSH_HOST}"
  validate_scalar WHISPER_SSH_USER "${WHISPER_SSH_USER}"
  validate_scalar WHISPER_SSH_IDENTITY_FILE "${WHISPER_SSH_IDENTITY_FILE}"
  validate_scalar WHISPER_SSH_CONFIG_FILE "${WHISPER_SSH_CONFIG_FILE}"
  validate_scalar WHISPER_SSH_CONFIG_FRAGMENT "${WHISPER_SSH_CONFIG_FRAGMENT}"
  validate_scalar WHISPER_WOL_PROXY_FILE "${WHISPER_WOL_PROXY_FILE}"
  validate_scalar WHISPER_WOL_BROADCAST "${WHISPER_WOL_BROADCAST}"
  validate_scalar WHISPER_WOL_MAC "${WHISPER_WOL_MAC}"

  [[ "${WHISPER_SSH_PORT}" =~ ^[0-9]+$ ]] || die_config "WHISPER_SSH_PORT 必须是数字"
  (( WHISPER_SSH_PORT >= 1 && WHISPER_SSH_PORT <= 65535 )) || die_config "WHISPER_SSH_PORT 超出范围"
  [[ "${WHISPER_WOL_WAIT_SECONDS}" =~ ^[0-9]+$ ]] || die_config "WHISPER_WOL_WAIT_SECONDS 必须是数字"
  (( WHISPER_WOL_WAIT_SECONDS >= 1 )) || die_config "WHISPER_WOL_WAIT_SECONDS 必须大于 0"
  [[ "${WHISPER_WOL_SEND_COUNT}" =~ ^[0-9]+$ ]] || die_config "WHISPER_WOL_SEND_COUNT 必须是数字"
  (( WHISPER_WOL_SEND_COUNT >= 1 )) || die_config "WHISPER_WOL_SEND_COUNT 必须大于 0"
  [[ "${WHISPER_SSH_CONNECT_TIMEOUT}" =~ ^[0-9]+$ ]] || die_config "WHISPER_SSH_CONNECT_TIMEOUT 必须是数字"
  [[ "${WHISPER_SSH_ALIVE_INTERVAL}" =~ ^[0-9]+$ ]] || die_config "WHISPER_SSH_ALIVE_INTERVAL 必须是数字"
  [[ "${WHISPER_SSH_ALIVE_COUNT_MAX}" =~ ^[0-9]+$ ]] || die_config "WHISPER_SSH_ALIVE_COUNT_MAX 必须是数字"
  [[ "${WHISPER_WOL_MAC}" =~ ^([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}$ ]] || \
    die_config "WHISPER_WOL_MAC 必须是 aa:bb:cc:dd:ee:ff 格式"
}

require_python() {
  WOL_PYTHON="$(command -v python3 || true)"
  [[ -n "${WOL_PYTHON}" && -x "${WOL_PYTHON}" ]] || die "控制端缺少 python3；WOL 代理需要它构造魔术包。"
}

write_wol_proxy() {
  local proxy_dir
  proxy_dir="$(dirname "${WHISPER_WOL_PROXY_FILE}")"
  mkdir -p "${proxy_dir}"
  chmod 700 "${proxy_dir}"

  cat >"${WHISPER_WOL_PROXY_FILE}" <<EOF
#!/bin/sh
set -eu

target_host="\${1:?missing SSH host}"
target_port="\${2:?missing SSH port}"
wake_broadcast="${WHISPER_WOL_BROADCAST}"
wake_mac="${WHISPER_WOL_MAC}"

"${WOL_PYTHON}" - "\${wake_broadcast}" "\${wake_mac}" "${WHISPER_WOL_SEND_COUNT}" <<'PY'
import socket
import sys

broadcast = sys.argv[1]
mac = bytes.fromhex(sys.argv[2].replace(":", ""))
send_count = int(sys.argv[3])
packet = b"\\xff" * 6 + mac * 16

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
for _ in range(send_count):
    sock.sendto(packet, (broadcast, 9))
sock.close()
PY

attempt=1
while [ "\${attempt}" -le "${WHISPER_WOL_WAIT_SECONDS}" ]; do
  if /usr/bin/nc -z -w 1 "\${target_host}" "\${target_port}" >/dev/null 2>&1; then
    exec /usr/bin/nc "\${target_host}" "\${target_port}"
  fi
  /bin/sleep 1
  attempt=\$((attempt + 1))
done

/usr/bin/printf '%s\\n' "Timed out waiting for \${target_host}:\${target_port} after Wake-on-LAN." >&2
exit 1
EOF
  chmod 700 "${WHISPER_WOL_PROXY_FILE}"
}

write_ssh_fragment() {
  local fragment_dir include_line
  fragment_dir="$(dirname "${WHISPER_SSH_CONFIG_FRAGMENT}")"
  include_line="Include ${WHISPER_SSH_CONFIG_FRAGMENT}"
  mkdir -p "${fragment_dir}"
  chmod 700 "${fragment_dir}"

  cat >"${WHISPER_SSH_CONFIG_FRAGMENT}" <<EOF
# Generated by whisper-custom-host/scripts/00-setup-ssh-wol.sh; local file, do not commit.
Host ${WHISPER_SSH_ALIAS} ${WHISPER_SSH_HOST}
    HostName ${WHISPER_SSH_HOST}
    User ${WHISPER_SSH_USER}
    Port ${WHISPER_SSH_PORT}
    IdentityFile ${WHISPER_SSH_IDENTITY_FILE}
    IdentitiesOnly yes
    ProxyCommand ${WHISPER_WOL_PROXY_FILE} %h %p
    ConnectTimeout ${WHISPER_SSH_CONNECT_TIMEOUT}
    AddKeysToAgent yes
    UseKeychain yes
    ServerAliveInterval ${WHISPER_SSH_ALIVE_INTERVAL}
    ServerAliveCountMax ${WHISPER_SSH_ALIVE_COUNT_MAX}
EOF
  chmod 600 "${WHISPER_SSH_CONFIG_FRAGMENT}"

  mkdir -p "$(dirname "${WHISPER_SSH_CONFIG_FILE}")"
  chmod 700 "$(dirname "${WHISPER_SSH_CONFIG_FILE}")"
  if [[ ! -f "${WHISPER_SSH_CONFIG_FILE}" ]]; then
    printf '%s\n' "${include_line}" >"${WHISPER_SSH_CONFIG_FILE}"
    chmod 600 "${WHISPER_SSH_CONFIG_FILE}"
  elif ! /usr/bin/grep -Fqx -- "${include_line}" "${WHISPER_SSH_CONFIG_FILE}"; then
    {
      printf '\n# whisper-custom-host SSH/WOL configuration\n'
      printf '%s\n' "${include_line}"
    } >>"${WHISPER_SSH_CONFIG_FILE}"
    chmod 600 "${WHISPER_SSH_CONFIG_FILE}"
  fi
}

check_config() {
  require_macos
  require_regular_user
  require_command ssh
  require_command nc
  validate_config
  require_python

  [[ -f "${WHISPER_SSH_CONFIG_FILE}" ]] || die "SSH 配置文件不存在：${WHISPER_SSH_CONFIG_FILE}；先运行 configure。"
  [[ -f "${WHISPER_SSH_CONFIG_FRAGMENT}" ]] || die "SSH 配置片段不存在：${WHISPER_SSH_CONFIG_FRAGMENT}；先运行 configure。"
  [[ -x "${WHISPER_WOL_PROXY_FILE}" ]] || die "WOL 代理不存在或不可执行：${WHISPER_WOL_PROXY_FILE}；先运行 configure。"

  if [[ -f "${WHISPER_SSH_IDENTITY_FILE}" ]]; then
    log "找到 SSH 私钥：${WHISPER_SSH_IDENTITY_FILE}"
  else
    warn "未找到 SSH 私钥：${WHISPER_SSH_IDENTITY_FILE}；请按 README 手动生成并授权公钥。"
  fi
  if [[ -f "${WHISPER_SSH_IDENTITY_FILE}.pub" ]]; then
    log "找到 SSH 公钥：${WHISPER_SSH_IDENTITY_FILE}.pub"
  else
    warn "未找到 SSH 公钥：${WHISPER_SSH_IDENTITY_FILE}.pub。"
  fi

  ssh -G -F "${WHISPER_SSH_CONFIG_FRAGMENT}" "${WHISPER_SSH_ALIAS}" >/dev/null
  log "SSH/WOL 本地配置检查通过：${WHISPER_SSH_ALIAS} -> ${WHISPER_SSH_HOST}:${WHISPER_SSH_PORT}"
}

configure() {
  require_macos
  require_regular_user
  require_command ssh
  require_command nc
  validate_config
  require_python
  write_wol_proxy
  write_ssh_fragment
  log "已生成 WOL 代理：${WHISPER_WOL_PROXY_FILE}"
  log "已生成 SSH 配置片段：${WHISPER_SSH_CONFIG_FRAGMENT}"
  if [[ ! -f "${WHISPER_SSH_IDENTITY_FILE}" ]]; then
    warn "尚未生成 SSH 私钥；脚本不会自动生成或复制私钥。"
  fi
  printf '下一步：按 README 的“SSH/WOL 前置设置”在 Mac mini 上开启 Remote Login、授权公钥并配置 pmset 与 ~/.ssh/rc。\n'
}

action="${1:-}"
case "${action}" in
  configure)
    configure
    ;;
  check)
    check_config
    ;;
  -h|--help)
    usage
    ;;
  *)
    usage
    [[ -z "${action}" ]] || exit 2
    ;;
esac
